"""App version. CI writes core/_version.py from the git tag at build time;
running from source falls back to a dev marker."""
try:
    from core._version import __version__  # generated by CI, gitignored
except Exception:
    __version__ = "0.0.0+dev"
